create database Examportal2
create table Internal(S_NO int NOT NULL  IDENTITY(1,1),
DEGREE VARCHAR(50)NULL,
BRANCH VARCHAR(20)NULL,
BATCH INT NOT NULL,
SEMESTER INT NOT NULL,
TYPEE VARCHAR(50),
CRITERIA VARCHAR(50),
SUBJECTT VARCHAR(50),
SECTION VARCHAR(50) NULL,
SUB_CAT VARCHAR(50)NULL,
SAME_SUB VARCHAR(50)NULL,
SUBJECT_CODE VARCHAR(50)NULL,
SUBJECT_NAME VARCHAR(50)NULL,
EXAM_DATE VARCHAR(50)NULL,
START_TIME VARCHAR(50)NULL,
END_TIME VARCHAR(50)NULL,
EXAM_DURATION VARCHAR(50)NULL,
SEL_SUB VARCHAR(50)NULL,
LOCK VARCHAR(50)NULL,
LOCKDATE VARCHAR(50)NULL,
MIN_MARK INT NULL,
MAX_MARK INT NULL,
V_I_P_STTNG VARCHAR(50) NULL,
PRIMARY KEY(S_NO));

SELECT*FROM Internal
DROP TABLE Internal;









DELETE FROM Internal WHERE S_NO=1144;

Delete from Internal Where S_NO<188;


create table sitemaster(S_NO int NOT NULL  IDENTITY(1,1),
DEGREE VARCHAR(50)NULL,
BRANCH VARCHAR(20)NULL,
BATCH INT NOT NULL,
SEMESTER INT NOT NULL,
TYPEE VARCHAR(50),
CRITERIA VARCHAR(50),
SUBJECTT VARCHAR(50),
PRIMARY KEY(S_NO));

